//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharkGym.DB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutina
    {
        public int PK_IdRutina { get; set; }
        public int ID_Cliente { get; set; }
        public int ID_Entrenador { get; set; }
        public string Ejercicio1 { get; set; }
        public string Ejercicio2 { get; set; }
        public string Ejercicio3 { get; set; }
        public string Ejercicio4 { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
